---
spring:
  profiles: dev
  application:
    name: cloud-greenwich-config-client-10002
  text: test1
--- 
spring:
  profiles: test
  application:
    name: cloud-greenwich-config-client-10002
  text: test 1
